blueprint:
  name: Aqara mini button
  description: Scene & device control using Aqara mini button
  domain: automation
  input:
    button_sensor:
      name: Aqara mini button
      description: Aqara mini button to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
          multiple: false
    single:
      name: Single press
      description: Action to run on a single press of the button
      default: []
      selector:
        action: {}
    double:
      name: Double press
      description: Action to run on a double press of the button
      default: []
      selector:
        action: {}
    hold:
      name: Hold
      description: Action to run when button is held
      default: []
      selector:
        action: {}
    release:
      name: Release
      description: Action to run when button is released
      default: []
      selector:
        action: {}
mode: parallel
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "button_sensor"
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'single' }}"
        sequence: !input "single"
      - conditions:
          - "{{ command == 'double' }}"
        sequence: !input "double"
      - conditions:
          - "{{ command == 'hold' }}"
        sequence: !input "hold"
      - conditions:
          - "{{ command == 'release' }}"
        sequence: !input "release"
